from subprocess import Popen, PIPE
import re

OSSEC_PATH = "/opt/ossec/bin/ossec-logtest"

tests_list = [("[SnmpBooster] [code 0102] Couldn't find 'loaded_by' configuration directive.",
               ["decoder: 'shinken-snmpbooster'",
                ]),
              ("[SnmpBooster] [code 0103] 'loaded_by' attribute must be in POLLER",
               ["decoder: 'shinken-snmpbooster'",
                "extra_data: 'POLLER'",
                ]),
              ("[SnmpBooster] [code 0201] Import error. Pysnmp is missing",
               ["decoder: 'shinken-snmpbooster'",
                ]),
              ("[SnmpBooster] [code 0202] [HOST, SERVICE] Not found in database",
               ["decoder: 'shinken-snmpbooster'",
                "url: 'HOST, SERVICE'",
                ]),
              ("[SnmpBooster] [code 0601] Import error. Pysnmp is missing",
               ["decoder: 'shinken-snmpbooster'",
                ]),
              ("[SnmpBooster] [code 0603] [HOST] ERROR",
               ["decoder: 'shinken-snmpbooster'",
                "url: 'HOST'",
                "extra_data: 'ERROR'",
                ]),
              ("[SnmpBooster] [code 0606] [HOST] SNMP Error: ERROR",
               ["decoder: 'shinken-snmpbooster'",
                "url: 'HOST'",
                "extra_data: 'ERROR'",
                ]),
              ("[SnmpBooster] [code 0607] [HOST, SERVICE] SNMP Error: ERROR",
               ["decoder: 'shinken-snmpbooster'",
                "url: 'HOST, SERVICE'",
                "extra_data: 'ERROR'",
                ]),
              ("[SnmpBooster] [code 0701] [HOST, SERVICE] "
               "DS BAD_DS not found to compute the trigger (TRIGGER). Please check your datasource file.",
               ["decoder: 'shinken-snmpbooster'",
                "url: 'HOST, SERVICE'",
                "status: 'BAD_DS'",
                "extra_data: 'TRIGGER'",
                ]),
              ("[SnmpBooster] [code 0704] [HOST, SERVICE] Trigger function error: found: ERROR",
               ["decoder: 'shinken-snmpbooster'",
                "url: 'HOST, SERVICE'",
                "extra_data: 'ERROR'",
                ]),
              ("[SnmpBooster] [code 0705] [HOST, SERVICE] Trigger function 'FUNCTION' not found",
               ["decoder: 'shinken-snmpbooster'",
                "url: 'HOST, SERVICE'",
                "extra_data: 'FUNCTION'",
                ]),
              ("[SnmpBooster] [code 0707] [HOST, SERVICE] RPN calculation Error: ERROR",
               ["decoder: 'shinken-snmpbooster'",
                "url: 'HOST, SERVICE'",
                "extra_data: 'ERROR'",
                ]),
              ("[SnmpBooster] [code 0709] [HOST, SERVICE] Trigger error: ERROR",
               ["decoder: 'shinken-snmpbooster'",
                "url: 'HOST, SERVICE'",
                "extra_data: 'ERROR'",
                ]),
              ("[SnmpBooster] [code 0901] Import error. Maybe one of this module is missing: ConfigObj",
               ["decoder: 'shinken-snmpbooster'",
                ]),
              ("[SnmpBooster] [code 0904] Datasource error while reading or merging in FILE: `ERROR'",
               ["decoder: 'shinken-snmpbooster'",
                "status: 'FILE'",
                "extra_data: 'ERROR'",
                ]),
              ("[SnmpBooster] [code 0905] Datasource error while reading or merging: `ERROR'",
               ["decoder: 'shinken-snmpbooster'",
                "extra_data: 'ERROR'",
                ]),
              ("[SnmpBooster] [code 0906] Error during the config conversion: ERROR",
               ["decoder: 'shinken-snmpbooster'",
                "extra_data: 'ERROR'",
                ]),
              ("[SnmpBooster] [code 0907] [HOST, SERVICE] ERROR",
               ["decoder: 'shinken-snmpbooster'",
                "url: 'HOST, SERVICE'",
                "extra_data: 'ERROR'",
                ]),
              ("[SnmpBooster] [code 0909] [HOST, SERVICE] ERROR",
               ["decoder: 'shinken-snmpbooster'",
                "url: 'HOST, SERVICE'",
                "extra_data: 'ERROR'",
                ]),
              ("[SnmpBooster] [code 1001]Command line { COMMAND LINE TEST } parsing error: PARSING fail",
               ["decoder: 'shinken-snmpbooster'",
                "status: 'COMMAND LINE TEST'",
                "extra_data: 'PARSING fail'",
                ]),
              ("[SnmpBooster] [code 1002][5] Exiting: EXITED",
               ["decoder: 'shinken-snmpbooster'",
                "status: '5'",
                "extra_data: 'EXITED'"
                ]),
              ("[SnmpBooster] [code 1003]FIX-ME-ID Exiting: EXITED",
               ["decoder: 'shinken-snmpbooster'",
                "extra_data: 'EXITED'"
                ]),
              ("[SnmpBooster] [code 1004] [HOST, SERVICE] Value type is not in "
               "'TEXT', 'STRING', DERIVE', 'GAUGE', 'COUNTER', 'DERIVE64', 'COUNTER64'",
               ["decoder: 'shinken-snmpbooster'",
                "url: 'HOST, SERVICE'"
                ]),
              ("[SnmpBooster] [code 1005] [HOST, SERVICE] EXCEPTION TEST",
               ["decoder: 'shinken-snmpbooster'",
                "url: 'HOST, SERVICE'"
                ]),
              ("[SnmpBooster] [code 1007] FIX-ME-ID Parent requests termination.",
               ["decoder: 'shinken-snmpbooster'",
                ]),
              ("[SnmpBooster] [code 1102] Please set datasource parameter",
               ["decoder: 'shinken-snmpbooster'",
                ]),
              ("[SnmpBooster] [code 1201] Import error. Pymongo seems missing.",
               ["decoder: 'shinken-snmpbooster'",
                ]),
              ("[SnmpBooster] [code 1202] MYSUPERDB Connection error: MY ERROR",
               ["decoder: 'shinken-snmpbooster'",
                "extra_data: 'MY ERROR'"
                ]),
              ("[SnmpBooster] [code 1203] CONTEXT error putting data in cache: ERROR",
               ["decoder: 'shinken-snmpbooster'",
                "status: 'CONTEXT'",
                "extra_data: 'ERROR'"
                ]),
              ("[SnmpBooster] [code 1204] [HOST, SERVICE] ERROR",
               ["decoder: 'shinken-snmpbooster'",
                "url: 'HOST, SERVICE'",
                "extra_data: 'ERROR'"
                ]),
              ("[SnmpBooster] [code 1206] [HOST, INSTANCE NAME] ERROR",
               ["decoder: 'shinken-snmpbooster'",
                "url: 'HOST, INSTANCE NAME'",
                "extra_data: 'ERROR'"
                ]),
              ("[SnmpBooster] [code 1207] [HOST, SERVICE] ERROR",
               ["decoder: 'shinken-snmpbooster'",
                "url: 'HOST, SERVICE'",
                "extra_data: 'ERROR'"
                ]),
              ("[SnmpBooster] [code 1208] [HOST] ERROR",
               ["decoder: 'shinken-snmpbooster'",
                "url: 'HOST'",
                "extra_data: 'ERROR'"
                ]),
              ("[SnmpBooster] [code 1301] Import error. Pymongo seems missing.",
               ["decoder: 'shinken-snmpbooster'",
                ]),
              ("[SnmpBooster] [code 1302] MYSUPERDB Connection error: MY ERROR",
               ["decoder: 'shinken-snmpbooster'",
                "extra_data: 'MY ERROR'"
                ]),
              ("[SnmpBooster] [code 1303] [HOST, SERVICE] ERROR",
               ["decoder: 'shinken-snmpbooster'",
                "url: 'HOST, SERVICE'",
                "extra_data: 'ERROR'"
                ]),
              ("[SnmpBooster] [code 1304] [HOST, SERVICE] ERROR",
               ["decoder: 'shinken-snmpbooster'",
                "url: 'HOST, SERVICE'",
                "extra_data: 'ERROR'"
                ]),
              ("[SnmpBooster] [code 1305] [HOST, SERVICE] ERROR",
               ["decoder: 'shinken-snmpbooster'",
                "url: 'HOST, SERVICE'",
                "extra_data: 'ERROR'"
                ]),
              ("[SnmpBooster] [code 1306] [HOST] ERROR",
               ["decoder: 'shinken-snmpbooster'",
                "url: 'HOST'",
                "extra_data: 'ERROR'"
                ]),
              ("[SnmpBooster] [code 1307] [HOST] Unknown service SERVICE",
               ["decoder: 'shinken-snmpbooster'",
                "url: 'HOST'",
                "extra_data: 'SERVICE'"
                ]),
              ("[SnmpBooster] [code 1308] [HOST] ERROR",
               ["decoder: 'shinken-snmpbooster'",
                "url: 'HOST'",
                "extra_data: 'ERROR'"
                ]),
              ]


for line, patterns in tests_list:
    logtest_p = Popen([OSSEC_PATH], stdin=PIPE, stdout=PIPE, stderr=PIPE)
    outputs = logtest_p.communicate(input=line)
    for pattern in patterns:
        #assert re.search(pattern, outputs[1]) is not None
        if re.search(pattern, outputs[1]) is None:
            import pdb;pdb.set_trace()
            print line, outputs[1], pattern

